#ifndef __ERROR_H__


#define INVALID_INPUT_EXCEPTION 1
#define MEMORY_ALOCATION_EXCEPTION 2

#define UNAVAILABLE_COLOR_EXCEPTION 3
#define INVALID_TERMINAL_SIZE 4


#define SUCCESS 0

typedef int Exception;

#endif